function dNEH = NavEq(t,UVW,VTP)
%UVW is body axes speed
%NEH is the North, East, height (speed in body axis?)
%PTP is Vee,Theta,Psi
dNEH = zeros(3,1);    % a column vector, emptied 
dNEH(1) = UVW(1)*cos(VTP(2))*cos(VTP(3))+...
          UVW(2)*(-cos(VTP(1))*sin(VTP(3))+sin(VTP(1))*sin(VTP(2))*cos(VTP(3)))+...
          UVW(3)*(sin(VTP(1))*sin(VTP(3))+cos(VTP(1))*sin(VTP(2))*cos(VTP(3)));
dNEH(2) = UVW(1)*cos(VTP(2))*sin(VTP(3))+...
          UVW(2)*(cos(VTP(1))*cos(VTP(3))+sin(VTP(1))*sin(VTP(2))*sin(VTP(3)))+...
          UVW(3)*(-sin(VTP(1))*cos(VTP(3))+cos(VTP(1))*sin(VTP(2))*sin(VTP(3)));
dNEH(3) = UVW(1)*sin(VTP(2))+...
          -UVW(2)*sin(VTP(1))*cos(VTP(2))+...
          -UVW(3)*cos(VTP(1))*cos(VTP(2));